import { ConflictException, Injectable, NotFoundException, UnprocessableEntityException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { AuditService } from '../../audit/audit.service';
import { DomainEventService } from '../../audit/domain-event.service';
import { TenantActorContext, TenantTransactionService } from '../../database/tenant-transaction.service';
import { CommandMeta, etagForUpdatedAt, MaintenanceCommandService } from '../maintenance-command.service';
import { FindingCreateDto, FindingPatchDto, InspectionAnswerUpsertDto, InspectionCreateDto, InspectionItemCreateDto, InspectionSectionCreateDto, InspectionTemplateCreateDto, InspectionTemplateVersionCreateDto } from './maintenance-inspections.dto';

@Injectable()
export class MaintenanceInspectionsService {
 constructor(private readonly tenant:TenantTransactionService,private readonly commands:MaintenanceCommandService,private readonly audit:AuditService,private readonly domain:DomainEventService){}
 private async template(ctx:TenantActorContext,id:string){const r=await this.tenant.run(ctx,tx=>tx.inspectionTemplate.findFirst({where:{id,tenantId:ctx.org}}));if(!r)throw new NotFoundException('INSPECTION_TEMPLATE_NOT_FOUND');return r}
 private async version(ctx:TenantActorContext,id:string){const r=await this.tenant.run(ctx,tx=>tx.inspectionTemplateVersion.findFirst({where:{id,tenantId:ctx.org}}));if(!r)throw new NotFoundException('INSPECTION_TEMPLATE_VERSION_NOT_FOUND');return r}
 private async section(ctx:TenantActorContext,id:string){const r=await this.tenant.run(ctx,tx=>tx.inspectionSection.findFirst({where:{id,tenantId:ctx.org}}));if(!r)throw new NotFoundException('INSPECTION_SECTION_NOT_FOUND');return r}
 private async inspection(ctx:TenantActorContext,id:string){const r=await this.tenant.run(ctx,tx=>tx.inspection.findFirst({where:{id,tenantId:ctx.org}}));if(!r)throw new NotFoundException('INSPECTION_NOT_FOUND');return r}
 private async finding(ctx:TenantActorContext,id:string){const r=await this.tenant.run(ctx,tx=>tx.finding.findFirst({where:{id,tenantId:ctx.org}}));if(!r)throw new NotFoundException('FINDING_NOT_FOUND');return r}
 private async bump(tx:Prisma.TransactionClient,model:'inspectionTemplate'|'inspectionTemplateVersion'|'inspectionSection'|'inspection'|'workOrder',ctx:TenantActorContext,id:string,updatedAt:Date){const next=new Date();const result=await (tx[model] as any).updateMany({where:{id,tenantId:ctx.org,updatedAt},data:{updatedAt:next,updatedBy:ctx.sub}});if(result.count!==1)throw new ConflictException('CONCURRENT_MODIFICATION');return (tx[model] as any).findFirstOrThrow({where:{id,tenantId:ctx.org}})}

 async createTemplate(ctx:TenantActorContext,input:InspectionTemplateCreateDto,meta:CommandMeta){return this.commands.execute(ctx,{operationScope:'maintenance.inspection_template.create',meta,requestBody:input},async tx=>{const row=await tx.inspectionTemplate.create({data:{tenantId:ctx.org,name:input.name,serviceType:input.serviceType,status:'ACTIVE',createdBy:ctx.sub,updatedBy:ctx.sub}});await this.audit.appendWith(tx,{event:'maintenance.inspection_template.created',actorId:ctx.sub,organizationId:ctx.org,entityType:'inspection_template',entityId:row.id,requestId:meta.requestId});return {body:row,updatedAt:row.updatedAt}})}
 async getTemplate(ctx:TenantActorContext,id:string){const row=await this.template(ctx,id);return {body:row,etag:etagForUpdatedAt(row.updatedAt)}}
 async listTemplates(ctx:TenantActorContext){return this.tenant.run(ctx,tx=>tx.inspectionTemplate.findMany({where:{tenantId:ctx.org},orderBy:{createdAt:'desc'}}))}
 async createVersion(ctx:TenantActorContext,templateId:string,input:InspectionTemplateVersionCreateDto,meta:CommandMeta){const current=await this.template(ctx,templateId);return this.commands.execute(ctx,{operationScope:`maintenance.inspection_template.${templateId}.version.create`,meta,requestBody:input,currentUpdatedAt:current.updatedAt},async tx=>{const last=await tx.inspectionTemplateVersion.findFirst({where:{tenantId:ctx.org,templateId},orderBy:{versionNumber:'desc'}});const row=await tx.inspectionTemplateVersion.create({data:{tenantId:ctx.org,templateId,versionNumber:(last?.versionNumber??0)+1,status:'DRAFT',effectiveFrom:input.effectiveFrom?new Date(input.effectiveFrom):null,createdBy:ctx.sub,updatedBy:ctx.sub}});const aggregate=await this.bump(tx,'inspectionTemplate',ctx,templateId,current.updatedAt);await this.audit.appendWith(tx,{event:'maintenance.inspection_template.version_created',actorId:ctx.sub,organizationId:ctx.org,entityType:'inspection_template_version',entityId:row.id,requestId:meta.requestId,metadata:{templateId,versionNumber:row.versionNumber}});return {body:row,updatedAt:aggregate.updatedAt}})}
 async getVersion(ctx:TenantActorContext,id:string){const row=await this.version(ctx,id);return {body:row,etag:etagForUpdatedAt(row.updatedAt)}}
 async listVersions(ctx:TenantActorContext,templateId:string){await this.template(ctx,templateId);return this.tenant.run(ctx,tx=>tx.inspectionTemplateVersion.findMany({where:{tenantId:ctx.org,templateId},orderBy:{versionNumber:'desc'}}))}

 async createSection(ctx:TenantActorContext,versionId:string,input:InspectionSectionCreateDto,meta:CommandMeta){const current=await this.version(ctx,versionId);if(current.status!=='DRAFT')throw new UnprocessableEntityException('INSPECTION_TEMPLATE_VERSION_IMMUTABLE');return this.commands.execute(ctx,{operationScope:`maintenance.inspection_template_version.${versionId}.section.create`,meta,requestBody:input,currentUpdatedAt:current.updatedAt},async tx=>{const row=await tx.inspectionSection.create({data:{tenantId:ctx.org,templateVersionId:versionId,title:input.title,displayOrder:input.displayOrder,createdBy:ctx.sub,updatedBy:ctx.sub}});await this.bump(tx,'inspectionTemplateVersion',ctx,versionId,current.updatedAt);await this.audit.appendWith(tx,{event:'maintenance.inspection_template.section_added',actorId:ctx.sub,organizationId:ctx.org,entityType:'inspection_section',entityId:row.id,requestId:meta.requestId,metadata:{templateVersionId:versionId}});return {body:row,updatedAt:row.updatedAt}})}
 async listSections(ctx:TenantActorContext,versionId:string){await this.version(ctx,versionId);return this.tenant.run(ctx,tx=>tx.inspectionSection.findMany({where:{tenantId:ctx.org,templateVersionId:versionId},orderBy:{displayOrder:'asc'}}))}

 async createItem(ctx:TenantActorContext,sectionId:string,input:InspectionItemCreateDto,meta:CommandMeta){const current=await this.section(ctx,sectionId);const version=await this.version(ctx,current.templateVersionId);if(version.status!=='DRAFT')throw new UnprocessableEntityException('INSPECTION_TEMPLATE_VERSION_IMMUTABLE');return this.commands.execute(ctx,{operationScope:`maintenance.inspection_section.${sectionId}.item.create`,meta,requestBody:input,currentUpdatedAt:current.updatedAt},async tx=>{const row=await tx.inspectionItem.create({data:{tenantId:ctx.org,sectionId,code:input.code,question:input.question,answerType:input.answerType as any,required:input.required,requiresEvidenceOnFail:input.requiresEvidenceOnFail,displayOrder:input.displayOrder,createdBy:ctx.sub,updatedBy:ctx.sub}});const aggregate=await this.bump(tx,'inspectionSection',ctx,sectionId,current.updatedAt);await tx.inspectionTemplateVersion.updateMany({where:{id:current.templateVersionId,tenantId:ctx.org},data:{updatedAt:new Date(),updatedBy:ctx.sub}});await this.audit.appendWith(tx,{event:'maintenance.inspection_template.item_added',actorId:ctx.sub,organizationId:ctx.org,entityType:'inspection_item',entityId:row.id,requestId:meta.requestId,metadata:{sectionId}});return {body:row,updatedAt:aggregate.updatedAt}})}
 async listItems(ctx:TenantActorContext,sectionId:string){await this.section(ctx,sectionId);return this.tenant.run(ctx,tx=>tx.inspectionItem.findMany({where:{tenantId:ctx.org,sectionId},orderBy:{displayOrder:'asc'}}))}
 private async transitionVersion(ctx:TenantActorContext,id:string,meta:CommandMeta,expected:string,next:string,auditEvent:string){const current=await this.version(ctx,id);return this.commands.execute(ctx,{operationScope:`maintenance.inspection_template_version.${id}.${next.toLowerCase()}`,meta,requestBody:{},currentUpdatedAt:current.updatedAt},async tx=>{if(next==='PUBLISHED'){const sections=await tx.inspectionSection.findMany({where:{tenantId:ctx.org,templateVersionId:id},select:{id:true}});if(!sections.length)throw new UnprocessableEntityException('INSPECTION_TEMPLATE_CONTENT_REQUIRED');const itemCount=await tx.inspectionItem.count({where:{tenantId:ctx.org,sectionId:{in:sections.map(x=>x.id)}}});if(!itemCount)throw new UnprocessableEntityException('INSPECTION_TEMPLATE_CONTENT_REQUIRED')}
 const data:any={status:next,updatedAt:new Date(),updatedBy:ctx.sub};if(next==='PUBLISHED')data.publishedAt=new Date();const changed=await tx.inspectionTemplateVersion.updateMany({where:{id,tenantId:ctx.org,updatedAt:current.updatedAt,status:expected as any},data});if(changed.count!==1)throw new UnprocessableEntityException('INVALID_TEMPLATE_VERSION_TRANSITION');const row=await tx.inspectionTemplateVersion.findFirstOrThrow({where:{id,tenantId:ctx.org}});await this.audit.appendWith(tx,{event:auditEvent,actorId:ctx.sub,organizationId:ctx.org,entityType:'inspection_template_version',entityId:id,requestId:meta.requestId,metadata:{from:expected,to:next}});return {body:row,updatedAt:row.updatedAt}})}
 submitReview(ctx:TenantActorContext,id:string,meta:CommandMeta){return this.transitionVersion(ctx,id,meta,'DRAFT','REVIEW','maintenance.inspection_template.review_submitted')}
 publishVersion(ctx:TenantActorContext,id:string,meta:CommandMeta){return this.transitionVersion(ctx,id,meta,'REVIEW','PUBLISHED','maintenance.inspection_template.published')}

 async createInspection(ctx:TenantActorContext,workOrderId:string,input:InspectionCreateDto,meta:CommandMeta){const wo=await this.tenant.run(ctx,tx=>tx.workOrder.findFirst({where:{id:workOrderId,tenantId:ctx.org}}));if(!wo)throw new NotFoundException('WORK_ORDER_NOT_FOUND');if(wo.status!=='IN_PROGRESS')throw new UnprocessableEntityException('WORK_ORDER_NOT_INSPECTION_READY');return this.commands.execute(ctx,{operationScope:`maintenance.work_order.${workOrderId}.inspection.create`,meta,requestBody:input,currentUpdatedAt:wo.updatedAt},async tx=>{const [version,technician]=await Promise.all([tx.inspectionTemplateVersion.findFirst({where:{id:input.templateVersionId,tenantId:ctx.org,status:'PUBLISHED'}}),tx.technician.findFirst({where:{id:input.performedBy,tenantId:ctx.org,status:'ACTIVE'}})]);if(!version)throw new UnprocessableEntityException('PUBLISHED_TEMPLATE_REQUIRED');if(!technician)throw new NotFoundException('TECHNICIAN_NOT_FOUND');const row=await tx.inspection.create({data:{tenantId:ctx.org,workOrderId,templateVersionId:input.templateVersionId,startedAt:new Date(),performedBy:input.performedBy,status:'DRAFT',createdBy:ctx.sub,updatedBy:ctx.sub}});const aggregate=await this.bump(tx,'workOrder',ctx,workOrderId,wo.updatedAt);await this.audit.appendWith(tx,{event:'maintenance.inspection.created',actorId:ctx.sub,organizationId:ctx.org,entityType:'inspection',entityId:row.id,requestId:meta.requestId,metadata:{workOrderId}});return {body:row,updatedAt:aggregate.updatedAt}})}
 async listWorkOrderInspections(ctx:TenantActorContext,workOrderId:string){const wo=await this.tenant.run(ctx,tx=>tx.workOrder.findFirst({where:{id:workOrderId,tenantId:ctx.org}}));if(!wo)throw new NotFoundException('WORK_ORDER_NOT_FOUND');return this.tenant.run(ctx,tx=>tx.inspection.findMany({where:{tenantId:ctx.org,workOrderId},orderBy:{createdAt:'desc'}}))}
 async getInspection(ctx:TenantActorContext,id:string){const row=await this.inspection(ctx,id);return {body:row,etag:etagForUpdatedAt(row.updatedAt)}}
 async startInspection(ctx:TenantActorContext,id:string,meta:CommandMeta){const current=await this.inspection(ctx,id);return this.commands.execute(ctx,{operationScope:`maintenance.inspection.${id}.start`,meta,requestBody:{},currentUpdatedAt:current.updatedAt},async tx=>{const changed=await tx.inspection.updateMany({where:{id,tenantId:ctx.org,updatedAt:current.updatedAt,status:'DRAFT'},data:{status:'IN_PROGRESS',startedAt:new Date(),updatedAt:new Date(),updatedBy:ctx.sub}});if(changed.count!==1)throw new UnprocessableEntityException('INVALID_INSPECTION_TRANSITION');const row=await tx.inspection.findFirstOrThrow({where:{id,tenantId:ctx.org}});await this.audit.appendWith(tx,{event:'maintenance.inspection.started',actorId:ctx.sub,organizationId:ctx.org,entityType:'inspection',entityId:id,requestId:meta.requestId});return {body:row,updatedAt:row.updatedAt}})}

 private answerValue(input:InspectionAnswerUpsertDto){return [input.answerBoolean!==undefined&&input.answerBoolean!==null,input.answerNumber!==undefined&&input.answerNumber!==null,input.answerText!==undefined&&input.answerText!==null,input.answerJson!==undefined&&input.answerJson!==null].filter(Boolean).length}
 async upsertAnswer(ctx:TenantActorContext,inspectionId:string,itemId:string,input:InspectionAnswerUpsertDto,meta:CommandMeta){const current=await this.inspection(ctx,inspectionId);if(current.status!=='IN_PROGRESS')throw new UnprocessableEntityException('INSPECTION_NOT_IN_PROGRESS');return this.commands.execute(ctx,{operationScope:`maintenance.inspection.${inspectionId}.answer.${itemId}`,meta,requestBody:input,currentUpdatedAt:current.updatedAt},async tx=>{const item=await tx.inspectionItem.findFirst({where:{id:itemId,tenantId:ctx.org}});if(!item)throw new NotFoundException('INSPECTION_ITEM_NOT_FOUND');const section=await tx.inspectionSection.findFirst({where:{id:item.sectionId,tenantId:ctx.org,templateVersionId:current.templateVersionId}});if(!section)throw new NotFoundException('INSPECTION_ITEM_NOT_FOUND');if(this.answerValue(input)!==1)throw new UnprocessableEntityException('INVALID_INSPECTION_ANSWER');const booleanType=['PASS_FAIL','YES_NO'].includes(item.answerType),numberType=['NUMBER','READING'].includes(item.answerType),textType=item.answerType==='TEXT';if(booleanType&&(input.answerBoolean===undefined||input.answerBoolean===null))throw new UnprocessableEntityException('INVALID_INSPECTION_ANSWER');if(numberType&&(input.answerNumber===undefined||input.answerNumber===null))throw new UnprocessableEntityException('INVALID_INSPECTION_ANSWER');if(textType&&(input.answerText===undefined||input.answerText===null))throw new UnprocessableEntityException('INVALID_INSPECTION_ANSWER');if(!booleanType&&!numberType&&!textType&&(input.answerJson===undefined||input.answerJson===null))throw new UnprocessableEntityException('INVALID_INSPECTION_ANSWER');const data:any={tenantId:ctx.org,inspectionId,inspectionItemId:itemId,answerBoolean:input.answerBoolean??null,answerNumber:input.answerNumber??null,answerText:input.answerText??null,answerJson:input.answerJson??undefined,result:input.result as any,recordedAt:new Date(input.recordedAt),recordedBy:current.performedBy,createdBy:ctx.sub,updatedBy:ctx.sub};const existing=await tx.inspectionAnswer.findFirst({where:{tenantId:ctx.org,inspectionId,inspectionItemId:itemId}});const row=existing?await tx.inspectionAnswer.update({where:{id:existing.id},data}):await tx.inspectionAnswer.create({data});const aggregate=await this.bump(tx,'inspection',ctx,inspectionId,current.updatedAt);await this.audit.appendWith(tx,{event:'maintenance.inspection.answer_recorded',actorId:ctx.sub,organizationId:ctx.org,entityType:'inspection',entityId:inspectionId,requestId:meta.requestId,metadata:{inspectionItemId:itemId,result:input.result}});return {body:row,updatedAt:aggregate.updatedAt}})}
 async listAnswers(ctx:TenantActorContext,inspectionId:string){await this.inspection(ctx,inspectionId);return this.tenant.run(ctx,tx=>tx.inspectionAnswer.findMany({where:{tenantId:ctx.org,inspectionId},orderBy:{recordedAt:'asc'}}))}
 async completeInspection(ctx:TenantActorContext,id:string,meta:CommandMeta){const current=await this.inspection(ctx,id);return this.commands.execute(ctx,{operationScope:`maintenance.inspection.${id}.complete`,meta,requestBody:{},currentUpdatedAt:current.updatedAt},async tx=>{if(current.status!=='IN_PROGRESS')throw new UnprocessableEntityException('INVALID_INSPECTION_TRANSITION');const sections=await tx.inspectionSection.findMany({where:{tenantId:ctx.org,templateVersionId:current.templateVersionId},select:{id:true}});const required=await tx.inspectionItem.findMany({where:{tenantId:ctx.org,sectionId:{in:sections.map(x=>x.id)},required:true},select:{id:true}});const answered=await tx.inspectionAnswer.count({where:{tenantId:ctx.org,inspectionId:id,inspectionItemId:{in:required.map(x=>x.id)}}});if(answered!==required.length)throw new UnprocessableEntityException('REQUIRED_INSPECTION_ANSWERS_MISSING');const changed=await tx.inspection.updateMany({where:{id,tenantId:ctx.org,updatedAt:current.updatedAt,status:'IN_PROGRESS'},data:{status:'COMPLETED',completedAt:new Date(),updatedAt:new Date(),updatedBy:ctx.sub}});if(changed.count!==1)throw new ConflictException('CONCURRENT_MODIFICATION');const wo=await tx.workOrder.updateMany({where:{id:current.workOrderId,tenantId:ctx.org,status:'IN_PROGRESS'},data:{status:'INSPECTION_COMPLETED',updatedAt:new Date(),updatedBy:ctx.sub}});if(wo.count!==1)throw new UnprocessableEntityException('WORK_ORDER_NOT_INSPECTION_READY');const row=await tx.inspection.findFirstOrThrow({where:{id,tenantId:ctx.org}});await this.audit.appendWith(tx,{event:'maintenance.inspection.completed',actorId:ctx.sub,organizationId:ctx.org,entityType:'inspection',entityId:id,requestId:meta.requestId,metadata:{workOrderId:current.workOrderId}});await this.domain.appendWith(tx,{tenantId:ctx.org,eventType:'maintenance.inspection.completed',aggregateType:'inspection',aggregateId:id,payload:{workOrderId:current.workOrderId,status:'COMPLETED'}});return {body:row,updatedAt:row.updatedAt}})}

 async createFinding(ctx:TenantActorContext,inspectionId:string,input:FindingCreateDto,meta:CommandMeta){const current=await this.inspection(ctx,inspectionId);if(current.status!=='COMPLETED')throw new UnprocessableEntityException('INSPECTION_NOT_COMPLETED');return this.commands.execute(ctx,{operationScope:`maintenance.inspection.${inspectionId}.finding.create`,meta,requestBody:input,currentUpdatedAt:current.updatedAt},async tx=>{if(input.inspectionItemId){const item=await tx.inspectionItem.findFirst({where:{id:input.inspectionItemId,tenantId:ctx.org}});if(!item)throw new NotFoundException('INSPECTION_ITEM_NOT_FOUND');const section=await tx.inspectionSection.findFirst({where:{id:item.sectionId,tenantId:ctx.org,templateVersionId:current.templateVersionId}});if(!section)throw new NotFoundException('INSPECTION_ITEM_NOT_FOUND')}if(input.findingClassificationId){const c=await tx.findingClassification.findFirst({where:{id:input.findingClassificationId,tenantId:ctx.org}});if(!c)throw new NotFoundException('FINDING_CLASSIFICATION_NOT_FOUND')}if(input.assetId){const asset=await tx.maintenanceAsset.findFirst({where:{id:input.assetId,tenantId:ctx.org}});if(!asset)throw new NotFoundException('MAINTENANCE_ASSET_NOT_FOUND')}const row=await tx.finding.create({data:{tenantId:ctx.org,workOrderId:current.workOrderId,inspectionId,inspectionItemId:input.inspectionItemId??null,assetId:input.assetId??null,findingClassificationId:input.findingClassificationId??null,findingType:input.findingType as any,category:input.category,title:input.title,description:input.description,severity:input.severity as any,riskLevel:input.riskLevel,status:'OPEN',detectedBy:current.performedBy,detectedAt:new Date(),createdBy:ctx.sub,updatedBy:ctx.sub}});await tx.inspection.updateMany({where:{id:inspectionId,tenantId:ctx.org,updatedAt:current.updatedAt},data:{updatedAt:new Date(),updatedBy:ctx.sub}});await tx.workOrder.updateMany({where:{id:current.workOrderId,tenantId:ctx.org,status:'INSPECTION_COMPLETED'},data:{status:'ACTION_REQUIRED',updatedAt:new Date(),updatedBy:ctx.sub}});const aggregate=await tx.inspection.findFirstOrThrow({where:{id:inspectionId,tenantId:ctx.org}});await this.audit.appendWith(tx,{event:'maintenance.finding.detected',actorId:ctx.sub,organizationId:ctx.org,entityType:'finding',entityId:row.id,requestId:meta.requestId,metadata:{inspectionId,workOrderId:current.workOrderId,severity:row.severity}});await this.domain.appendWith(tx,{tenantId:ctx.org,eventType:'maintenance.finding.detected',aggregateType:'finding',aggregateId:row.id,payload:{inspectionId,workOrderId:current.workOrderId,severity:row.severity,status:row.status}});return {body:row,updatedAt:aggregate.updatedAt}})}
 async listFindings(ctx:TenantActorContext){return this.tenant.run(ctx,tx=>tx.finding.findMany({where:{tenantId:ctx.org},orderBy:{detectedAt:'desc'}}))}
 async listInspectionFindings(ctx:TenantActorContext,inspectionId:string){await this.inspection(ctx,inspectionId);return this.tenant.run(ctx,tx=>tx.finding.findMany({where:{tenantId:ctx.org,inspectionId},orderBy:{detectedAt:'desc'}}))}
 async getFinding(ctx:TenantActorContext,id:string){const row=await this.finding(ctx,id);return {body:row,etag:etagForUpdatedAt(row.updatedAt)}}
 async patchFinding(ctx:TenantActorContext,id:string,input:FindingPatchDto,meta:CommandMeta){const current=await this.finding(ctx,id);if(!['OPEN','ACKNOWLEDGED'].includes(current.status))throw new UnprocessableEntityException('FINDING_NOT_EDITABLE');return this.commands.execute(ctx,{operationScope:`maintenance.finding.${id}.patch`,meta,requestBody:input,currentUpdatedAt:current.updatedAt},async tx=>{const row=await tx.finding.update({where:{id},data:{...input,severity:input.severity as any,updatedAt:new Date(),updatedBy:ctx.sub}});await this.audit.appendWith(tx,{event:'maintenance.finding.updated',actorId:ctx.sub,organizationId:ctx.org,entityType:'finding',entityId:id,requestId:meta.requestId,metadata:{changed:Object.keys(input)}});return {body:row,updatedAt:row.updatedAt}})}
}
