import { Body, Controller, Get, Headers, HttpCode, Param, Patch, Post, Put, Res } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { CurrentUser, Roles } from '../../security/auth.decorators';
import { CommandMeta } from '../maintenance-command.service';
import { MAINTENANCE_INSPECTION_WRITE_ROLES, MAINTENANCE_READ_ROLES } from '../maintenance.roles';
import { FindingCreateDto, FindingPatchDto, InspectionAnswerUpsertDto, InspectionCreateDto, InspectionItemCreateDto, InspectionSectionCreateDto, InspectionTemplateCreateDto, InspectionTemplateVersionCreateDto } from './maintenance-inspections.dto';
import { MaintenanceInspectionsService } from './maintenance-inspections.service';

const meta=(key?:string,ifMatch?:string,requestId?:string):CommandMeta=>({idempotencyKey:key??'',ifMatch,requestId:requestId??randomUUID()});
const etag=(res:any,value:string)=>res.setHeader('ETag',value);

@Controller('maintenance')
export class MaintenanceInspectionsController {
 constructor(private readonly service:MaintenanceInspectionsService){}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('inspection-templates') listTemplates(@CurrentUser() c:any){return this.service.listTemplates(c)}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('inspection-templates') async createTemplate(@CurrentUser() c:any,@Body() b:InspectionTemplateCreateDto,@Headers('idempotency-key') k:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.createTemplate(c,b,meta(k,undefined,r));etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('inspection-templates/:templateId') async getTemplate(@CurrentUser() c:any,@Param('templateId') id:string,@Res({passthrough:true}) res:any){const o=await this.service.getTemplate(c,id);etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('inspection-templates/:templateId/versions') listVersions(@CurrentUser() c:any,@Param('templateId') id:string){return this.service.listVersions(c,id)}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('inspection-templates/:templateId/versions') async createVersion(@CurrentUser() c:any,@Param('templateId') id:string,@Body() b:InspectionTemplateVersionCreateDto,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.createVersion(c,id,b,meta(k,m,r));etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('inspection-template-versions/:versionId') async getVersion(@CurrentUser() c:any,@Param('versionId') id:string,@Res({passthrough:true}) res:any){const o=await this.service.getVersion(c,id);etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('inspection-template-versions/:versionId/sections') listSections(@CurrentUser() c:any,@Param('versionId') id:string){return this.service.listSections(c,id)}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('inspection-template-versions/:versionId/sections') async createSection(@CurrentUser() c:any,@Param('versionId') id:string,@Body() b:InspectionSectionCreateDto,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.createSection(c,id,b,meta(k,m,r));etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('inspection-sections/:sectionId/items') listItems(@CurrentUser() c:any,@Param('sectionId') id:string){return this.service.listItems(c,id)}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('inspection-sections/:sectionId/items') async createItem(@CurrentUser() c:any,@Param('sectionId') id:string,@Body() b:InspectionItemCreateDto,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.createItem(c,id,b,meta(k,m,r));etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('inspection-template-versions/:versionId/submit-review') @HttpCode(200) async submitReview(@CurrentUser() c:any,@Param('versionId') id:string,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.submitReview(c,id,meta(k,m,r));etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('inspection-template-versions/:versionId/publish') @HttpCode(200) async publish(@CurrentUser() c:any,@Param('versionId') id:string,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.publishVersion(c,id,meta(k,m,r));etag(res,o.etag);return o.body}

 @Roles(...MAINTENANCE_READ_ROLES) @Get('work-orders/:workOrderId/inspections') listInspections(@CurrentUser() c:any,@Param('workOrderId') id:string){return this.service.listWorkOrderInspections(c,id)}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('work-orders/:workOrderId/inspections') async createInspection(@CurrentUser() c:any,@Param('workOrderId') id:string,@Body() b:InspectionCreateDto,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.createInspection(c,id,b,meta(k,m,r));etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('inspections/:inspectionId') async getInspection(@CurrentUser() c:any,@Param('inspectionId') id:string,@Res({passthrough:true}) res:any){const o=await this.service.getInspection(c,id);etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('inspections/:inspectionId/start') @HttpCode(200) async startInspection(@CurrentUser() c:any,@Param('inspectionId') id:string,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.startInspection(c,id,meta(k,m,r));etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Put('inspections/:inspectionId/answers/:inspectionItemId') async upsertAnswer(@CurrentUser() c:any,@Param('inspectionId') inspectionId:string,@Param('inspectionItemId') itemId:string,@Body() b:InspectionAnswerUpsertDto,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.upsertAnswer(c,inspectionId,itemId,b,meta(k,m,r));etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('inspections/:inspectionId/answers') listAnswers(@CurrentUser() c:any,@Param('inspectionId') id:string){return this.service.listAnswers(c,id)}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('inspections/:inspectionId/complete') @HttpCode(200) async completeInspection(@CurrentUser() c:any,@Param('inspectionId') id:string,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.completeInspection(c,id,meta(k,m,r));etag(res,o.etag);return o.body}

 @Roles(...MAINTENANCE_READ_ROLES) @Get('findings') listFindings(@CurrentUser() c:any){return this.service.listFindings(c)}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('inspections/:inspectionId/findings') listInspectionFindings(@CurrentUser() c:any,@Param('inspectionId') id:string){return this.service.listInspectionFindings(c,id)}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Post('inspections/:inspectionId/findings') async createFinding(@CurrentUser() c:any,@Param('inspectionId') id:string,@Body() b:FindingCreateDto,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.createFinding(c,id,b,meta(k,m,r));etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('findings/:findingId') async getFinding(@CurrentUser() c:any,@Param('findingId') id:string,@Res({passthrough:true}) res:any){const o=await this.service.getFinding(c,id);etag(res,o.etag);return o.body}
 @Roles(...MAINTENANCE_INSPECTION_WRITE_ROLES) @Patch('findings/:findingId') async patchFinding(@CurrentUser() c:any,@Param('findingId') id:string,@Body() b:FindingPatchDto,@Headers('idempotency-key') k:string|undefined,@Headers('if-match') m:string|undefined,@Headers('x-request-id') r:string|undefined,@Res({passthrough:true}) res:any){const o=await this.service.patchFinding(c,id,b,meta(k,m,r));etag(res,o.etag);return o.body}
}
