import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { PrismaService } from '../database/prisma.service';
import { AuditService } from '../audit/audit.service';

@Injectable()
export class ProcurementService {
  constructor(private readonly db:PrismaService, private readonly audit:AuditService) {}
  private async project(ctx:any,id:string){const p=await this.db.project.findFirst({where:{id,organizationId:ctx.org}});if(!p)throw new NotFoundException('PROJECT_NOT_FOUND');return p}
  private async requirement(ctx:any,id:string){const r=await this.db.materialRequirement.findFirst({where:{id,organizationId:ctx.org},include:{items:true}});if(!r)throw new NotFoundException('MATERIAL_REQUIREMENT_NOT_FOUND');return r}
  private async rfq(ctx:any,id:string){const r=await this.db.rfq.findFirst({where:{id,organizationId:ctx.org},include:{quotes:{include:{items:true}}}});if(!r)throw new NotFoundException('RFQ_NOT_FOUND');return r}
  private async quote(ctx:any,id:string){const q=await this.db.supplierQuote.findFirst({where:{id,rfq:{organizationId:ctx.org}},include:{items:true,rfq:true}});if(!q)throw new NotFoundException('SUPPLIER_QUOTE_NOT_FOUND');return q}

  async createRequirement(ctx:any,projectId:string,input:any){
    await this.project(ctx,projectId);
    const boq=await this.db.boq.findFirst({where:{id:input.boqId,projectId,organizationId:ctx.org},include:{versions:{where:{version:Number(input.version)},include:{items:true}}}});
    const v=boq?.versions?.[0]; if(!boq||!v)throw new NotFoundException('BOQ_VERSION_NOT_FOUND'); if(v.status!=='APPROVED')throw new ConflictException('BOQ_NOT_APPROVED');
    const requested:Array<any>=Array.isArray(input.items)&&input.items.length?input.items:v.items.map((x:any)=>({boqItemId:x.id,quantity:x.quantity}));
    const allowed=new Map(v.items.map((x:any)=>[x.id,Number(x.quantity)]));
    for(const item of requested){const max=allowed.get(item.boqItemId);if(max===undefined||Number(item.quantity)<=0||Number(item.quantity)>max)throw new BadRequestException('INVALID_REQUIREMENT_ITEM')}
    const out=await this.db.materialRequirement.create({data:{id:randomUUID(),organizationId:ctx.org,projectId,boqVersionId:v.id,requestedBy:ctx.sub,items:{create:requested.map((x:any)=>({id:randomUUID(),boqItemId:x.boqItemId,quantity:x.quantity}))}},include:{items:true}});
    await this.audit.append({event:'MATERIAL_REQUIREMENT_CREATED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:projectId,requestId:'api',metadata:{requirementId:out.id,boqId:boq.id,version:v.version}});return out;
  }
  async listRequirements(ctx:any,projectId:string){await this.project(ctx,projectId);return this.db.materialRequirement.findMany({where:{organizationId:ctx.org,projectId},include:{items:true,rfqs:true},orderBy:{createdAt:'desc'}})}
  async submitRequirement(ctx:any,id:string){const r=await this.requirement(ctx,id);if(r.status!=='DRAFT')throw new ConflictException('REQUIREMENT_NOT_DRAFT');const out=await this.db.materialRequirement.update({where:{id},data:{status:'SUBMITTED'}});await this.audit.append({event:'MATERIAL_REQUIREMENT_SUBMITTED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:r.projectId,requestId:'api',metadata:{requirementId:id}});return out}
  async approveRequirement(ctx:any,id:string){const r=await this.requirement(ctx,id);if(r.status!=='SUBMITTED')throw new ConflictException('REQUIREMENT_NOT_SUBMITTED');const out=await this.db.materialRequirement.update({where:{id},data:{status:'APPROVED'}});await this.audit.append({event:'MATERIAL_REQUIREMENT_APPROVED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:r.projectId,requestId:'api',metadata:{requirementId:id}});return out}
  async createRfq(ctx:any,requirementId:string,input:any){const r=await this.requirement(ctx,requirementId);if(r.status!=='APPROVED')throw new ConflictException('REQUIREMENT_NOT_APPROVED');const out=await this.db.rfq.create({data:{id:randomUUID(),organizationId:ctx.org,projectId:r.projectId,materialRequirementId:r.id,dueAt:input?.dueAt?new Date(input.dueAt):undefined}});await this.audit.append({event:'RFQ_CREATED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:r.projectId,requestId:'api',metadata:{rfqId:out.id,requirementId:r.id}});return out}
  async issueRfq(ctx:any,id:string){const r=await this.rfq(ctx,id);if(r.status!=='DRAFT')throw new ConflictException('RFQ_NOT_DRAFT');const out=await this.db.rfq.update({where:{id},data:{status:'ISSUED'}});await this.audit.append({event:'RFQ_ISSUED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:r.projectId,requestId:'api',metadata:{rfqId:id}});return out}
  async createSupplier(ctx:any,input:any){if(!input?.name)throw new BadRequestException('SUPPLIER_NAME_REQUIRED');return this.db.supplier.create({data:{id:randomUUID(),organizationId:ctx.org,name:input.name,taxNumber:input.taxNumber,email:input.email,phone:input.phone}})}
  async createQuote(ctx:any,rfqId:string,input:any){const r=await this.rfq(ctx,rfqId);if(r.status!=='ISSUED')throw new ConflictException('RFQ_NOT_ISSUED');const supplier=await this.db.supplier.findFirst({where:{id:input.supplierId,organizationId:ctx.org}});if(!supplier)throw new NotFoundException('SUPPLIER_NOT_FOUND');if(!Array.isArray(input.items)||!input.items.length)throw new BadRequestException('QUOTE_ITEMS_REQUIRED');const out=await this.db.supplierQuote.create({data:{id:randomUUID(),rfqId,supplierId:supplier.id,currency:input.currency??'SAR',leadTimeDays:input.leadTimeDays,paymentTerms:input.paymentTerms,items:{create:input.items.map((x:any)=>({id:randomUUID(),boqItemId:x.boqItemId,quantity:x.quantity,unitPrice:x.unitPrice,availableQty:x.availableQty}))}},include:{items:true}});await this.audit.append({event:'SUPPLIER_QUOTE_CREATED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:r.projectId,requestId:'api',metadata:{rfqId,quoteId:out.id,supplierId:supplier.id}});return out}
  async submitQuote(ctx:any,id:string){const q=await this.quote(ctx,id);if(q.status!=='DRAFT')throw new ConflictException('QUOTE_NOT_DRAFT');const out=await this.db.supplierQuote.update({where:{id},data:{status:'SUBMITTED',submittedAt:new Date()}});await this.audit.append({event:'SUPPLIER_QUOTE_SUBMITTED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:q.rfq.projectId,requestId:'api',metadata:{quoteId:id,rfqId:q.rfqId}});return out}
  async comparison(ctx:any,id:string){const r=await this.rfq(ctx,id);return r.quotes.filter((q:any)=>q.status==='SUBMITTED'||q.status==='SELECTED').map((q:any)=>({quoteId:q.id,supplierId:q.supplierId,currency:q.currency,leadTimeDays:q.leadTimeDays,paymentTerms:q.paymentTerms,total:q.items.reduce((s:number,i:any)=>s+Number(i.quantity)*Number(i.unitPrice),0),items:q.items}))}
  async award(ctx:any,id:string,quoteId:string){const r=await this.rfq(ctx,id);if(r.status!=='ISSUED')throw new ConflictException('RFQ_NOT_OPEN');const q=r.quotes.find((x:any)=>x.id===quoteId);if(!q||q.status!=='SUBMITTED')throw new BadRequestException('QUOTE_NOT_ELIGIBLE');await this.db.$transaction([this.db.supplierQuote.updateMany({where:{rfqId:id,status:'SUBMITTED'},data:{status:'REJECTED'}}),this.db.supplierQuote.update({where:{id:quoteId},data:{status:'SELECTED'}}),this.db.rfq.update({where:{id},data:{status:'AWARDED'}})]);await this.audit.append({event:'RFQ_AWARDED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:r.projectId,requestId:'api',metadata:{rfqId:id,quoteId,supplierId:q.supplierId}});return {rfqId:id,quoteId,status:'AWARDED'}}
  async createPurchaseOrder(ctx:any,rfqId:string,input:any){const r=await this.rfq(ctx,rfqId);if(r.status!=='AWARDED')throw new ConflictException('RFQ_NOT_AWARDED');const selected=r.quotes.find((x:any)=>x.status==='SELECTED');if(!selected)throw new ConflictException('NO_SELECTED_QUOTE');const poNumber=input?.poNumber??`PO-${Date.now()}`;const boqItems=await this.db.boqItem.findMany({where:{id:{in:selected.items.map((i:any)=>i.boqItemId)}}});const map=new Map(boqItems.map((i:any)=>[i.id,i]));const po=await this.db.purchaseOrder.create({data:{id:randomUUID(),organizationId:ctx.org,projectId:r.projectId,supplierId:selected.supplierId,supplierQuoteId:selected.id,poNumber,items:{create:selected.items.map((i:any)=>{const b:any=map.get(i.boqItemId);return{id:randomUUID(),boqItemId:i.boqItemId,description:b?.description??'BOQ Item',unit:b?.unit??'EA',quantity:i.quantity,unitPrice:i.unitPrice}})}},include:{items:true}});await this.audit.append({event:'PURCHASE_ORDER_CREATED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:r.projectId,requestId:'api',metadata:{poId:po.id,poNumber,rfqId}});return po}
  async approvePurchaseOrder(ctx:any,id:string){const po=await this.db.purchaseOrder.findFirst({where:{id,organizationId:ctx.org}});if(!po)throw new NotFoundException('PURCHASE_ORDER_NOT_FOUND');if(po.status!=='DRAFT')throw new ConflictException('PURCHASE_ORDER_NOT_DRAFT');const out=await this.db.purchaseOrder.update({where:{id},data:{status:'APPROVED',approvedAt:new Date()}});await this.audit.append({event:'PURCHASE_ORDER_APPROVED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:po.projectId,requestId:'api',metadata:{poId:id,poNumber:po.poNumber}});return out}
  async listPurchaseOrders(ctx:any,projectId:string){await this.project(ctx,projectId);return this.db.purchaseOrder.findMany({where:{organizationId:ctx.org,projectId},include:{items:true,deliveries:true},orderBy:{createdAt:'desc'}})}
}
