import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { PrismaService } from '../database/prisma.service';
import { AuditService } from '../audit/audit.service';
@Injectable()
export class InventoryService {
 constructor(private readonly db:PrismaService,private readonly audit:AuditService){}
 private async project(ctx:any,id:string){const p=await this.db.project.findFirst({where:{id,organizationId:ctx.org}});if(!p)throw new NotFoundException('PROJECT_NOT_FOUND');return p}
 private async warehouse(ctx:any,id:string){const w=await this.db.warehouse.findFirst({where:{id,organizationId:ctx.org}});if(!w)throw new NotFoundException('WAREHOUSE_NOT_FOUND');return w}
 async createWarehouse(ctx:any,input:any){if(!input?.name)throw new BadRequestException('WAREHOUSE_NAME_REQUIRED');return this.db.warehouse.create({data:{id:randomUUID(),organizationId:ctx.org,name:input.name,city:input.city}})}
 warehouses(ctx:any){return this.db.warehouse.findMany({where:{organizationId:ctx.org},orderBy:{name:'asc'}})}
 private signed(type:string,q:number){if(type==='PURCHASE_RECEIPT'||type==='PROJECT_RETURN')return q;if(type==='PROJECT_ALLOCATION'||type==='SUPPLIER_RETURN')return -q;return 0}
 async balance(ctx:any,warehouseId:string){await this.warehouse(ctx,warehouseId);const rows=await this.db.inventoryMovement.findMany({where:{organizationId:ctx.org,warehouseId},orderBy:{occurredAt:'asc'}});const map=new Map<string,number>();for(const r of rows){if(!r.boqItemId)continue;map.set(r.boqItemId,(map.get(r.boqItemId)??0)+this.signed(r.movementType,Number(r.quantity)))}return [...map.entries()].map(([boqItemId,quantity])=>({boqItemId,quantity}))}
 async allocate(ctx:any,projectId:string,input:any){await this.project(ctx,projectId);await this.warehouse(ctx,input.warehouseId);const qty=Number(input.quantity);if(!input.boqItemId||qty<=0)throw new BadRequestException('INVALID_ALLOCATION');const b=await this.balance(ctx,input.warehouseId);const available=b.find(x=>x.boqItemId===input.boqItemId)?.quantity??0;if(available<qty)throw new BadRequestException('INSUFFICIENT_STOCK');const row=await this.db.inventoryMovement.create({data:{id:randomUUID(),organizationId:ctx.org,warehouseId:input.warehouseId,projectId,boqItemId:input.boqItemId,movementType:'PROJECT_ALLOCATION',quantity:qty,referenceType:'PROJECT',referenceId:projectId}});await this.audit.append({event:'MATERIAL_ALLOCATED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:projectId,requestId:'api',metadata:{movementId:row.id,boqItemId:input.boqItemId,quantity:qty,warehouseId:input.warehouseId}});return row}
 async issue(ctx:any,projectId:string,input:any){await this.project(ctx,projectId);await this.warehouse(ctx,input.warehouseId);const qty=Number(input.quantity);if(!input.boqItemId||qty<=0)throw new BadRequestException('INVALID_ISSUE');const rows=await this.db.inventoryMovement.findMany({where:{organizationId:ctx.org,projectId,boqItemId:input.boqItemId,warehouseId:input.warehouseId}});const allocated=rows.filter((r:any)=>r.movementType==='PROJECT_ALLOCATION').reduce((s:number,r:any)=>s+Number(r.quantity),0), issued=rows.filter((r:any)=>r.movementType==='PROJECT_ISSUE').reduce((s:number,r:any)=>s+Number(r.quantity),0), returned=rows.filter((r:any)=>r.movementType==='PROJECT_RETURN').reduce((s:number,r:any)=>s+Number(r.quantity),0);if(allocated-issued+returned<qty)throw new BadRequestException('ISSUE_EXCEEDS_ALLOCATION');const row=await this.db.inventoryMovement.create({data:{id:randomUUID(),organizationId:ctx.org,warehouseId:input.warehouseId,projectId,boqItemId:input.boqItemId,movementType:'PROJECT_ISSUE',quantity:qty,referenceType:'PROJECT',referenceId:projectId}});await this.audit.append({event:'MATERIAL_ISSUED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:projectId,requestId:'api',metadata:{movementId:row.id,boqItemId:input.boqItemId,quantity:qty}});return row}
 async returnMaterial(ctx:any,projectId:string,input:any){await this.project(ctx,projectId);await this.warehouse(ctx,input.warehouseId);const qty=Number(input.quantity);if(!input.boqItemId||qty<=0)throw new BadRequestException('INVALID_RETURN');const rows=await this.db.inventoryMovement.findMany({where:{organizationId:ctx.org,projectId,boqItemId:input.boqItemId,warehouseId:input.warehouseId}});const issued=rows.filter((r:any)=>r.movementType==='PROJECT_ISSUE').reduce((s:number,r:any)=>s+Number(r.quantity),0), returned=rows.filter((r:any)=>r.movementType==='PROJECT_RETURN').reduce((s:number,r:any)=>s+Number(r.quantity),0);if(issued-returned<qty)throw new BadRequestException('RETURN_EXCEEDS_ISSUED');const row=await this.db.inventoryMovement.create({data:{id:randomUUID(),organizationId:ctx.org,warehouseId:input.warehouseId,projectId,boqItemId:input.boqItemId,movementType:'PROJECT_RETURN',quantity:qty,referenceType:'PROJECT',referenceId:projectId}});await this.audit.append({event:'MATERIAL_RETURNED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:projectId,requestId:'api',metadata:{movementId:row.id,boqItemId:input.boqItemId,quantity:qty}});return row}
 async projectMaterials(ctx:any,projectId:string){await this.project(ctx,projectId);return this.db.inventoryMovement.findMany({where:{organizationId:ctx.org,projectId},orderBy:{occurredAt:'asc'}})}
}
