import { Body, Controller, Get, Headers, HttpCode, Param, Post, Res } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { CurrentUser, Roles } from '../../security/auth.decorators';
import { LifecycleCommandDto } from '../contracts/maintenance-contracts.dto';
import { CommandMeta } from '../maintenance-command.service';
import { MAINTENANCE_OPERATIONS_WRITE_ROLES, MAINTENANCE_READ_ROLES, MAINTENANCE_TECHNICIAN_WRITE_ROLES } from '../maintenance.roles';
import { MaintenanceVisitCreateDto, TechnicianCreateDto, WorkOrderAssignmentCreateDto, WorkOrderCreateDto } from './maintenance-operations.dto';
import { MaintenanceOperationsService } from './maintenance-operations.service';

const meta=(key?:string,ifMatch?:string,requestId?:string):CommandMeta=>({idempotencyKey:key??'',ifMatch,requestId:requestId??randomUUID()});
const setEtag=(res:any,etag:string)=>res.setHeader('ETag',etag);

@Controller('maintenance')
export class MaintenanceOperationsController {
 constructor(private readonly service:MaintenanceOperationsService){}

 @Roles(...MAINTENANCE_READ_ROLES) @Get('technicians') listTechnicians(@CurrentUser() ctx:any){return this.service.listTechnicians(ctx)}
 @Roles(...MAINTENANCE_TECHNICIAN_WRITE_ROLES) @Post('technicians') async createTechnician(@CurrentUser() ctx:any,@Body() body:TechnicianCreateDto,@Headers('idempotency-key') key:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.createTechnician(ctx,body,meta(key,undefined,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('technicians/:technicianId') async getTechnician(@CurrentUser() ctx:any,@Param('technicianId') id:string,@Res({passthrough:true}) res:any){const out=await this.service.getTechnician(ctx,id);setEtag(res,out.etag);return out.body}

 @Roles(...MAINTENANCE_READ_ROLES) @Get('contracts/:contractId/visits') listVisits(@CurrentUser() ctx:any,@Param('contractId') id:string){return this.service.listVisits(ctx,id)}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('contracts/:contractId/visits') async createVisit(@CurrentUser() ctx:any,@Param('contractId') id:string,@Body() body:MaintenanceVisitCreateDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.createVisit(ctx,id,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('visits/:visitId') async getVisit(@CurrentUser() ctx:any,@Param('visitId') id:string,@Res({passthrough:true}) res:any){const out=await this.service.getVisit(ctx,id);setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('visits/:visitId/schedule') @HttpCode(200) async scheduleVisit(@CurrentUser() ctx:any,@Param('visitId') id:string,@Body() body:LifecycleCommandDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.scheduleVisit(ctx,id,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('visits/:visitId/confirm') @HttpCode(200) async confirmVisit(@CurrentUser() ctx:any,@Param('visitId') id:string,@Body() body:LifecycleCommandDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.confirmVisit(ctx,id,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('visits/:visitId/arrive') @HttpCode(200) async arriveVisit(@CurrentUser() ctx:any,@Param('visitId') id:string,@Body() body:LifecycleCommandDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.arriveVisit(ctx,id,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('visits/:visitId/start') @HttpCode(200) async startVisit(@CurrentUser() ctx:any,@Param('visitId') id:string,@Body() body:LifecycleCommandDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.startVisit(ctx,id,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('visits/:visitId/complete') @HttpCode(200) async completeVisit(@CurrentUser() ctx:any,@Param('visitId') id:string,@Body() body:LifecycleCommandDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.completeVisit(ctx,id,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}

 @Roles(...MAINTENANCE_READ_ROLES) @Get('work-orders') listWorkOrders(@CurrentUser() ctx:any){return this.service.listWorkOrders(ctx)}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('visits/:visitId/work-orders') listVisitWorkOrders(@CurrentUser() ctx:any,@Param('visitId') visitId:string){return this.service.listVisitWorkOrders(ctx,visitId)}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('visits/:visitId/work-orders') async createWorkOrder(@CurrentUser() ctx:any,@Param('visitId') visitId:string,@Body() body:WorkOrderCreateDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.createWorkOrder(ctx,visitId,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('work-orders/:workOrderId') async getWorkOrder(@CurrentUser() ctx:any,@Param('workOrderId') id:string,@Res({passthrough:true}) res:any){const out=await this.service.getWorkOrder(ctx,id);setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_READ_ROLES) @Get('work-orders/:workOrderId/assignments') listAssignments(@CurrentUser() ctx:any,@Param('workOrderId') id:string){return this.service.listAssignments(ctx,id)}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('work-orders/:workOrderId/assignments') async assign(@CurrentUser() ctx:any,@Param('workOrderId') id:string,@Body() body:WorkOrderAssignmentCreateDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.assignWorkOrder(ctx,id,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('work-orders/:workOrderId/assignments/:assignmentId/accept') @HttpCode(200) async accept(@CurrentUser() ctx:any,@Param('workOrderId') workOrderId:string,@Param('assignmentId') assignmentId:string,@Body() body:LifecycleCommandDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.acceptAssignment(ctx,workOrderId,assignmentId,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('work-orders/:workOrderId/arrive') @HttpCode(200) async arriveWorkOrder(@CurrentUser() ctx:any,@Param('workOrderId') id:string,@Body() body:LifecycleCommandDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.arriveWorkOrder(ctx,id,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
 @Roles(...MAINTENANCE_OPERATIONS_WRITE_ROLES) @Post('work-orders/:workOrderId/start') @HttpCode(200) async startWorkOrder(@CurrentUser() ctx:any,@Param('workOrderId') id:string,@Body() body:LifecycleCommandDto,@Headers('idempotency-key') key:string|undefined,@Headers('if-match') ifMatch:string|undefined,@Headers('x-request-id') requestId:string|undefined,@Res({passthrough:true}) res:any){const out=await this.service.startWorkOrder(ctx,id,body,meta(key,ifMatch,requestId));setEtag(res,out.etag);return out.body}
}
