import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { PrismaService } from '../database/prisma.service';
import { AuditService } from '../audit/audit.service';
@Injectable() export class BoqService {
 constructor(private db:PrismaService,private audit:AuditService){}
 private async project(ctx:any,id:string){const p=await this.db.project.findFirst({where:{id,organizationId:ctx.org}});if(!p)throw new NotFoundException('PROJECT_NOT_FOUND');return p}
 private async boq(ctx:any,id:string){const b=await this.db.boq.findFirst({where:{id,organizationId:ctx.org},include:{versions:{include:{items:true},orderBy:{version:'asc'}}}});if(!b)throw new NotFoundException('BOQ_NOT_FOUND');return b}
 async create(ctx:any,projectId:string,input:any){await this.project(ctx,projectId);if(!input.title)throw new BadRequestException('BOQ_TITLE_REQUIRED');const id=randomUUID();const b=await this.db.boq.create({data:{id,organizationId:ctx.org,projectId,title:input.title,versions:{create:{id:randomUUID(),version:1,status:'DRAFT'}}},include:{versions:true}});await this.audit.append({event:'BOQ_CREATED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:projectId,requestId:'api',metadata:{boqId:id}});return b}
 async list(ctx:any,projectId:string){await this.project(ctx,projectId);return this.db.boq.findMany({where:{organizationId:ctx.org,projectId},include:{versions:{orderBy:{version:'desc'},take:1}},orderBy:{createdAt:'desc'}})}
 get(ctx:any,id:string){return this.boq(ctx,id)}
 async addItem(ctx:any,id:string,version:number,input:any){const b=await this.boq(ctx,id);const v=b.versions.find((x:any)=>x.version===version);if(!v)throw new NotFoundException('BOQ_VERSION_NOT_FOUND');if(v.status!=='DRAFT')throw new ConflictException('BOQ_VERSION_LOCKED');if(!input.description||!input.unit||Number(input.quantity)<=0)throw new BadRequestException('INVALID_BOQ_ITEM');const item=await this.db.boqItem.create({data:{id:randomUUID(),versionId:v.id,lineNo:input.lineNo,description:input.description,itemCode:input.itemCode,category:input.category,manufacturer:input.manufacturer,model:input.model,unit:input.unit,quantity:input.quantity,unitPrice:input.unitPrice,specification:input.specification}});await this.audit.append({event:'BOQ_ITEM_ADDED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:b.projectId,requestId:'api',metadata:{boqId:id,version,lineNo:input.lineNo}});return item}
 async submit(ctx:any,id:string,version:number){const b=await this.boq(ctx,id);const v=b.versions.find((x:any)=>x.version===version);if(!v)throw new NotFoundException('BOQ_VERSION_NOT_FOUND');if(v.status!=='DRAFT')throw new ConflictException('BOQ_VERSION_NOT_DRAFT');if(!v.items.length)throw new BadRequestException('BOQ_EMPTY');const out=await this.db.boqVersion.update({where:{id:v.id},data:{status:'SUBMITTED',submittedAt:new Date()}});await this.db.boq.update({where:{id},data:{status:'SUBMITTED'}});await this.audit.append({event:'BOQ_SUBMITTED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:b.projectId,requestId:'api',metadata:{boqId:id,version}});return out}
 async approve(ctx:any,id:string,version:number){const b=await this.boq(ctx,id);const v=b.versions.find((x:any)=>x.version===version);if(!v)throw new NotFoundException('BOQ_VERSION_NOT_FOUND');if(v.status!=='SUBMITTED')throw new ConflictException('BOQ_VERSION_NOT_SUBMITTED');await this.db.boqVersion.updateMany({where:{boqId:id,status:'APPROVED'},data:{status:'SUPERSEDED'}});const out=await this.db.boqVersion.update({where:{id:v.id},data:{status:'APPROVED',approvedAt:new Date(),approvedBy:ctx.sub}});await this.db.boq.update({where:{id},data:{status:'APPROVED',currentVersion:version}});await this.audit.append({event:'BOQ_APPROVED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:b.projectId,requestId:'api',metadata:{boqId:id,version}});return out}
 async reject(ctx:any,id:string,version:number,input:any){const b=await this.boq(ctx,id);const v=b.versions.find((x:any)=>x.version===version);if(!v)throw new NotFoundException('BOQ_VERSION_NOT_FOUND');if(v.status!=='SUBMITTED')throw new ConflictException('BOQ_VERSION_NOT_SUBMITTED');const out=await this.db.boqVersion.update({where:{id:v.id},data:{status:'REJECTED',changeReason:input.reason??'Rejected'}});await this.db.boq.update({where:{id},data:{status:'REJECTED'}});await this.audit.append({event:'BOQ_REJECTED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:b.projectId,requestId:'api',metadata:{boqId:id,version,reason:input.reason}});return out}
 async newVersion(ctx:any,id:string,input:any){const b=await this.boq(ctx,id);const latest=b.versions[b.versions.length-1];if(latest.status!=='APPROVED'&&latest.status!=='REJECTED')throw new ConflictException('CURRENT_VERSION_NOT_CLOSED');const n=latest.version+1;const v=await this.db.boqVersion.create({data:{id:randomUUID(),boqId:id,version:n,status:'DRAFT',changeReason:input.changeReason,items:{create:latest.items.map((i:any)=>({id:randomUUID(),lineNo:i.lineNo,itemCode:i.itemCode,description:i.description,category:i.category,manufacturer:i.manufacturer,model:i.model,unit:i.unit,quantity:i.quantity,unitPrice:i.unitPrice,specification:i.specification}))}},include:{items:true}});await this.db.boq.update({where:{id},data:{currentVersion:n,status:'DRAFT'}});await this.audit.append({event:'BOQ_VERSION_CREATED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:b.projectId,requestId:'api',metadata:{boqId:id,version:n,fromVersion:latest.version}});return v}
}
