import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { PrismaService } from '../database/prisma.service';
import { AuditService } from '../audit/audit.service';
@Injectable()
export class DeliveryService {
 constructor(private readonly db:PrismaService,private readonly audit:AuditService){}
 private async delivery(ctx:any,id:string){const d=await this.db.delivery.findFirst({where:{id,organizationId:ctx.org},include:{items:{include:{purchaseOrderItem:true}},purchaseOrder:{include:{items:true}}}});if(!d)throw new NotFoundException('DELIVERY_NOT_FOUND');return d}
 async create(ctx:any,poId:string,input:any){const po=await this.db.purchaseOrder.findFirst({where:{id:poId,organizationId:ctx.org},include:{items:true}});if(!po)throw new NotFoundException('PURCHASE_ORDER_NOT_FOUND');if(po.status!=='APPROVED'&&po.status!=='PARTIALLY_DELIVERED')throw new ConflictException('PURCHASE_ORDER_NOT_DELIVERABLE');if(!Array.isArray(input.items)||!input.items.length)throw new BadRequestException('DELIVERY_ITEMS_REQUIRED');const map=new Map(po.items.map((x:any)=>[x.id,Number(x.quantity)]));for(const i of input.items){const max=map.get(i.purchaseOrderItemId);if(max===undefined||Number(i.arrivedQty)<=0||Number(i.arrivedQty)>max)throw new BadRequestException('INVALID_DELIVERY_ITEM')}
 const number=input.deliveryNumber??`DEL-${Date.now()}`;const out=await this.db.delivery.create({data:{id:randomUUID(),organizationId:ctx.org,projectId:po.projectId,purchaseOrderId:po.id,deliveryNumber:number,items:{create:input.items.map((x:any)=>({id:randomUUID(),purchaseOrderItemId:x.purchaseOrderItemId,arrivedQty:x.arrivedQty}))}},include:{items:true}});await this.audit.append({event:'DELIVERY_CREATED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:po.projectId,requestId:'api',metadata:{deliveryId:out.id,poId}});return out}
 get(ctx:any,id:string){return this.delivery(ctx,id)}
 async arrive(ctx:any,id:string){const d=await this.delivery(ctx,id);if(d.status!=='EXPECTED')throw new ConflictException('DELIVERY_NOT_EXPECTED');const out=await this.db.delivery.update({where:{id},data:{status:'ARRIVED',arrivedAt:new Date()}});await this.audit.append({event:'DELIVERY_ARRIVED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:d.projectId,requestId:'api',metadata:{deliveryId:id}});return out}
 async inspect(ctx:any,id:string,input:any){const d=await this.delivery(ctx,id);if(d.status!=='ARRIVED'&&d.status!=='UNDER_INSPECTION')throw new ConflictException('DELIVERY_NOT_INSPECTABLE');if(!Array.isArray(input.items)||!input.items.length)throw new BadRequestException('INSPECTION_ITEMS_REQUIRED');const byId=new Map(d.items.map((x:any)=>[x.id,x]));for(const i of input.items){const row:any=byId.get(i.deliveryItemId);if(!row)throw new BadRequestException('DELIVERY_ITEM_NOT_FOUND');const accepted=Number(i.acceptedQty??0), rejected=Number(i.rejectedQty??0), damaged=Number(i.damagedQty??0), arrived=Number(row.arrivedQty);if(accepted<0||rejected<0||damaged<0||accepted+rejected+damaged>arrived)throw new BadRequestException('INVALID_INSPECTION_TOTAL')}
 await this.db.$transaction(input.items.map((i:any)=>this.db.deliveryItem.update({where:{id:i.deliveryItemId},data:{acceptedQty:i.acceptedQty??0,rejectedQty:i.rejectedQty??0,damagedQty:i.damagedQty??0}})));const updated=await this.delivery(ctx,id);const a=updated.items.reduce((s:number,x:any)=>s+Number(x.acceptedQty),0), r=updated.items.reduce((s:number,x:any)=>s+Number(x.rejectedQty)+Number(x.damagedQty),0);const status=a>0&&r>0?'PARTIALLY_ACCEPTED':a>0?'ACCEPTED':'REJECTED';const out=await this.db.delivery.update({where:{id},data:{status}});await this.audit.append({event:'GOODS_INSPECTED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:d.projectId,requestId:'api',metadata:{deliveryId:id,accepted:a,rejected:r,status}});return out}
 async receive(ctx:any,id:string,warehouseId:string){const d=await this.delivery(ctx,id);if(!['ACCEPTED','PARTIALLY_ACCEPTED'].includes(d.status))throw new ConflictException('DELIVERY_NOT_ACCEPTED');if(d.receivedAt)throw new ConflictException('DELIVERY_ALREADY_RECEIVED');const warehouse=await this.db.warehouse.findFirst({where:{id:warehouseId,organizationId:ctx.org}});if(!warehouse)throw new NotFoundException('WAREHOUSE_NOT_FOUND');const moves=d.items.filter((x:any)=>Number(x.acceptedQty)>0).map((x:any)=>this.db.inventoryMovement.create({data:{id:randomUUID(),organizationId:ctx.org,warehouseId,projectId:d.projectId,boqItemId:x.purchaseOrderItem.boqItemId,movementType:'PURCHASE_RECEIPT',quantity:x.acceptedQty,unitCost:x.purchaseOrderItem.unitPrice,referenceType:'DELIVERY',referenceId:d.id}}));await this.db.$transaction(moves);const out=await this.db.delivery.update({where:{id},data:{receivedAt:new Date()}});const all=await this.db.delivery.findMany({where:{purchaseOrderId:d.purchaseOrderId,receivedAt:{not:null}},include:{items:true}});const acceptedByItem=new Map<string,number>();for(const del of all){for(const item of del.items){acceptedByItem.set(item.purchaseOrderItemId,(acceptedByItem.get(item.purchaseOrderItemId)??0)+Number(item.acceptedQty))}}const fully=d.purchaseOrder.items.every((item:any)=>(acceptedByItem.get(item.id)??0)>=Number(item.quantity));const poStatus=fully?'FULLY_DELIVERED':'PARTIALLY_DELIVERED';await this.db.purchaseOrder.update({where:{id:d.purchaseOrderId},data:{status:poStatus}});await this.audit.append({event:'INVENTORY_RECEIVED',actorId:ctx.sub,organizationId:ctx.org,entityType:'project',entityId:d.projectId,requestId:'api',metadata:{deliveryId:id,warehouseId,accepted:d.items.reduce((s:number,x:any)=>s+Number(x.acceptedQty),0)}});return out}
}
