'use client';
import {useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api/v1';
const supplierId='01900000-0000-7000-8000-000000000401';
const warehouseId='01900000-0000-7000-8000-000000000301';
export default function Pilot(){
 const [running,setRunning]=useState(false);const [log,setLog]=useState<string[]>([]);const [kpi,setKpi]=useState<any>(null);
 const add=(s:string)=>setLog(x=>[...x,s]);
 async function api(path:string,method='GET',body?:any){const token=localStorage.getItem('muqawil_access_token');if(!token)throw Error('LOGIN_REQUIRED');const r=await fetch(`${API}${path}`,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(`${method} ${path}: ${j?.message??r.status}`);return j}
 async function run(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setRunning(true);setLog([]);setKpi(null);const f=new FormData(e.currentTarget);try{
  const stamp=Date.now();
  const project=await api('/projects','POST',{name:f.get('project'),clientName:f.get('client'),city:f.get('city'),scope:'Fire systems'});add(`✓ Project ${project.id}`);
  const boq=await api(`/projects/${project.id}/boqs`,'POST',{title:'Pilot BOQ'});const item=await api(`/boqs/${boq.id}/versions/1/items`,'POST',{lineNo:1,description:f.get('item'),unit:'EA',quantity:Number(f.get('qty')),unitPrice:Number(f.get('budgetPrice'))});await api(`/boqs/${boq.id}/versions/1/submit`,'POST',{});await api(`/boqs/${boq.id}/versions/1/approve`,'POST',{});add('✓ BOQ approved');
  const mr=await api(`/projects/${project.id}/material-requirements`,'POST',{boqId:boq.id,version:1,items:[{boqItemId:item.id,quantity:Number(f.get('qty'))}]});await api(`/material-requirements/${mr.id}/submit`,'POST',{});await api(`/material-requirements/${mr.id}/approve`,'POST',{});add('✓ Material Requirement approved');
  const rfq=await api(`/material-requirements/${mr.id}/rfqs`,'POST',{});await api(`/rfqs/${rfq.id}/issue`,'POST',{});const quote=await api(`/rfqs/${rfq.id}/quotes`,'POST',{supplierId,leadTimeDays:2,paymentTerms:'30 days',items:[{boqItemId:item.id,quantity:Number(f.get('qty')),unitPrice:Number(f.get('quotePrice')),availableQty:Number(f.get('qty'))}]});await api(`/supplier-quotes/${quote.id}/submit`,'POST',{});await api(`/rfqs/${rfq.id}/award`,'POST',{quoteId:quote.id});add('✓ RFQ / Quote / Award');
  const po=await api(`/rfqs/${rfq.id}/purchase-orders`,'POST',{poNumber:`PO-PILOT-${stamp}`});await api(`/purchase-orders/${po.id}/approve`,'POST',{});add('✓ Purchase Order approved');
  const delivery=await api(`/purchase-orders/${po.id}/deliveries`,'POST',{deliveryNumber:`DEL-PILOT-${stamp}`,items:[{purchaseOrderItemId:po.items[0].id,arrivedQty:Number(f.get('arrived'))}]});await api(`/deliveries/${delivery.id}/arrive`,'POST',{});await api(`/deliveries/${delivery.id}/inspect`,'POST',{items:[{deliveryItemId:delivery.items[0].id,acceptedQty:Number(f.get('accepted')),rejectedQty:Number(f.get('rejected')),damagedQty:0}]});await api(`/deliveries/${delivery.id}/receive`,'POST',{warehouseId});add('✓ Delivery inspected and received');
  await api(`/projects/${project.id}/materials/allocate`,'POST',{warehouseId,boqItemId:item.id,quantity:Number(f.get('allocate'))});add('✓ Project allocation posted');
  const metrics=await api(`/projects/${project.id}/materials/kpis`);setKpi(metrics);add('✓ KPI verified');const audit=await api(`/projects/${project.id}/activity`);add(`✓ Audit events: ${audit.length}`);
 }catch(err:any){add(`✗ ${err.message}`)}finally{setRunning(false)}}
 return <><h1>وحدة تجربة MVP الميدانية</h1><p className="muted">تشغّل دورة S4–S8 كاملة على مشروع تجريبي واحد بعد تسجيل الدخول.</p><form className="card" onSubmit={run}><div className="grid"><label>المشروع<input className="field" name="project" defaultValue="مشروع تجربة أنظمة الحريق"/></label><label>العميل<input className="field" name="client" defaultValue="عميل تجريبي"/></label><label>المدينة<input className="field" name="city" defaultValue="جازان"/></label><label>الصنف<input className="field" name="item" defaultValue="Fire sprinkler"/></label><label>الكمية المطلوبة<input className="field" name="qty" type="number" defaultValue="10"/></label><label>سعر BOQ<input className="field" name="budgetPrice" type="number" defaultValue="25"/></label><label>سعر المورد<input className="field" name="quotePrice" type="number" defaultValue="20"/></label><label>وصل<input className="field" name="arrived" type="number" defaultValue="8"/></label><label>مقبول<input className="field" name="accepted" type="number" defaultValue="7"/></label><label>مرفوض<input className="field" name="rejected" type="number" defaultValue="1"/></label><label>تخصيص للمشروع<input className="field" name="allocate" type="number" defaultValue="5"/></label></div><button className="btn" disabled={running}>{running?'جاري التنفيذ...':'تشغيل رحلة MVP كاملة'}</button></form><div className="grid"><div className="card"><h3>سجل التنفيذ</h3>{log.map((x,i)=><p key={i}>{x}</p>)}</div><div className="card"><h3>Material KPIs</h3><pre style={{whiteSpace:'pre-wrap'}}>{kpi?JSON.stringify(kpi,null,2):'—'}</pre></div></div></>}
