export const MAINTENANCE_READ_ROLES=['PLATFORM_ADMIN','TENANT_ADMIN','ORG_ADMIN','OPERATIONS_MANAGER','PROJECT_MANAGER','DISPATCHER','TECHNICIAN','INSPECTOR','CLIENT_USER','CLIENT_APPROVER'] as const;
export const MAINTENANCE_CONTRACT_WRITE_ROLES=['PLATFORM_ADMIN','TENANT_ADMIN','ORG_ADMIN','OPERATIONS_MANAGER','PROJECT_MANAGER','CONTRACT_MANAGER'] as const;
export const MAINTENANCE_OPERATIONS_WRITE_ROLES=['PLATFORM_ADMIN','TENANT_ADMIN','ORG_ADMIN','OPERATIONS_MANAGER','PROJECT_MANAGER','DISPATCHER'] as const;
export const MAINTENANCE_TECHNICIAN_WRITE_ROLES=['PLATFORM_ADMIN','TENANT_ADMIN','ORG_ADMIN','OPERATIONS_MANAGER','PROJECT_MANAGER','ENGINEER'] as const;
export const MAINTENANCE_INSPECTION_WRITE_ROLES=['PLATFORM_ADMIN','TENANT_ADMIN','ORG_ADMIN','OPERATIONS_MANAGER','PROJECT_MANAGER','TECHNICIAN','INSPECTOR','ENGINEER'] as const;
